name: Flake8
on:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Run Flake8
      run: |
        python -m pip install flake8
        flake8        
